name: Test JS

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
           node-version: 20


      - name: Instalar dependencias
        run: npm ci || npm install

      - name: Ejecutar tests
        run: npm test
